name: PEP8 Python Code

on:
  push:
    branches: [ main, master, python_basic, python_typing, python_oop ]
  pull_request:
    branches: [ main, master, python_basic, python_typing, python_oop ]

jobs:
  lint:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'
        
    - name: Install pycodestyle
      run: pip install pycodestyle
      
    - name: Run pycodestyle
      run: pycodestyle .
